CREATE TABLE RESIDENTE (
   CPF VARCHAR(11) PRIMARY KEY,
   NOME VARCHAR(40) NOT NULL,
   IDADE NUMBER(3),
   SEXO CHAR(1),
   ENDCEP CHAR(8),
   ENDRUA VARCHAR(50),
   ENDNUM CHAR(5),
   TEL1 VARCHAR(11),
   TEL2 VARCHAR(11),
   TEL3 VARCHAR(11),
   INSTITUICAO VARCHAR(30),
   REMUNERACAO NUMBER(6,2) NOT NULL
);

CREATE TABLE MEDICO (
   CPF VARCHAR(11) PRIMARY KEY,
   NOME VARCHAR(40) NOT NULL,
   IDADE NUMBER(3),
   SEXO CHAR(1),
   ENDCEP CHAR(8),
   ENDRUA VARCHAR(50),
   ENDNUM CHAR(5),
   TEL1 VARCHAR(11),
   TEL2 VARCHAR(11),
   TEL3 VARCHAR(11),
   REMUNERACAO NUMBER(6,2) NOT NULL,
   CPF_CHEFE VARCHAR(11) ,
   CONSTRAINT FK_CPFCHEFE FOREIGN KEY (CPF_CHEFE) REFERENCES MEDICO (CPF)
);

CREATE TABLE ESPECIALIZACAO (
    CPF VARCHAR (11),
    ESPECIALIZACAO VARCHAR (30),
    CONSTRAINT PK_ESPECIALIZACAO PRIMARY KEY (CPF,ESPECIALIZACAO),
    CONSTRAINT FK_CPFESPECIALIZACAO FOREIGN KEY (CPF) REFERENCES MEDICO(CPF)
);

CREATE TABLE DEPARTAMENTO (
    COD CHAR (5) PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE TRABALHA_MED (
    CPF VARCHAR (11),
    COD CHAR (5),
    CONSTRAINT PK_TRABALHA PRIMARY KEY (CPF,COD),
    CONSTRAINT FK_CPFTRABALHA FOREIGN KEY (CPF) REFERENCES MEDICO(CPF),
    CONSTRAINT FK_CODTRABALHA FOREIGN KEY (COD) REFERENCES DEPARTAMENTO(COD)
);

CREATE TABLE ENFERMEIRO (
    CPF VARCHAR (11),
    COD CHAR (5) NOT NULL,
    NOME VARCHAR (40) NOT NULL,
    SEXO CHAR(1),
    ENDCEP CHAR(8),
    ENDRUA VARCHAR(50),
    ENDNUM CHAR(5),
    TEL1 VARCHAR(11),
    TEL2 VARCHAR(11),
    TEL3 VARCHAR(11),
    REMUNERACAO NUMBER(6,2) NOT NULL,
    CONSTRAINT PK_ENFERMEIRO PRIMARY KEY (CPF),
    CONSTRAINT FK_ENFERMEIRO FOREIGN KEY (COD) REFERENCES DEPARTAMENTO(COD)
);

CREATE TABLE PACIENTE (
   CPF VARCHAR(11) PRIMARY KEY,
   NOME VARCHAR(40) NOT NULL,
   IDADE NUMBER(3),
   SEXO CHAR(1),
   ENDCEP CHAR(8),
   ENDRUA VARCHAR(50),
   ENDNUM CHAR(5),
   TEL1 VARCHAR(11),
   TEL2 VARCHAR(11),
   TEL3 VARCHAR(11),
   CPF_AUXILIAR VARCHAR(11) UNIQUE,
   CONSTRAINT FK_ENFERMEIROAUX FOREIGN KEY (CPF_AUXILIAR) REFERENCES ENFERMEIRO (CPF)
);

CREATE TABLE CIRURGIA (
    CPF_R VARCHAR(11) NOT NULL,
    CPF_M VARCHAR(11) NOT NULL,
    CPF_P VARCHAR(11) NOT NULL,
    
    CONSTRAINT PK_CIRURGIA PRIMARY KEY (CPF_R, CPF_M),
    CONSTRAINT FK_CPFRESIDENTE FOREIGN KEY (CPF_R) REFERENCES RESIDENTE (CPF),
    CONSTRAINT FK_CPFMED FOREIGN KEY (CPF_M) REFERENCES MEDICO (CPF),
    CONSTRAINT FK_CPFPAC FOREIGN KEY (CPF_P) REFERENCES PACIENTE (CPF)
);

CREATE TABLE CONSULTA (
    CPF_P VARCHAR(11) NOT NULL,
    CPF_M VARCHAR(11) NOT NULL,
    DATA_CONSULTA DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_CONSULTA PRIMARY KEY(CPF_P, CPF_M, DATA_CONSULTA),
    CONSTRAINT FK_CPFPACIENTE FOREIGN KEY (CPF_P) REFERENCES PACIENTE(CPF),
    CONSTRAINT FK_CPFMEDICO FOREIGN KEY (CPF_M) REFERENCES MEDICO(CPF)
);

CREATE TABLE RECEITA (
    CPF_P VARCHAR(11) NOT NULL, 
    CPF_M VARCHAR(11) NOT NULL, 
    DATA_CONSULTA DATE NOT NULL,
    ID CHAR(10) NOT NULL,
    MEDICAMENTO VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_RECEITA PRIMARY KEY (CPF_P, CPF_M, DATA_CONSULTA, ID),
    CONSTRAINT FK_CONSULTA FOREIGN KEY (CPF_P, CPF_M, DATA_CONSULTA) REFERENCES CONSULTA(CPF_P, CPF_M, DATA_CONSULTA)
);